### ISSUE TITLE
add intermediate HTML-only representation

### ISSUE THREAD

**Issue by pw374** [ocaml/omd#128]
In some next version (hopefully in the next few days for 1.2.0), I plan on changing the way the backend produces HTML: it will build an instance of `Omd_backend.html` (a type that doesn't exist yet) before converting to a string. So the HTML output will likely be somewhat slower, but it'll be easier to work with.

Or I could just add an abstract backend without modifying the current one in order to preserve the current performance... We'll see...

If anyone has any thoughts about this, please feel free to comment! ;)

**Comment by shepard8** [comment]
Did you think about using TyXML type representation for that purpose?

This would ensure you create only valid values (currently you may have Omd.Url inside Omd.Url elements).

Also, as markdown is mainly used for the web, it makes sense to use web-oriented representations instead of creating a new one which would require some glue before being usable by those libraries.

In addition, HTML conversion is already handled by TyXML.

**Comment by nojb** [comment]
There is a simple intermediate HTML language in `master`, see https://github.com/ocaml/omd/blob/01614cc0227303224e3f39cb5e85d40a7774180d/src/html.mli#L4-L13
