### ISSUE TITLE
What is the difference between Ul and Ulp?

### ISSUE THREAD

**Issue by lindig** [ocaml/omd#154]
The abstract representation of Markdown in `omd.mli` provides `Ul` and `Ulp` for unnumbered lists but both are isomorphic. What is the purpose of having two?

```
type element =
| H1 of t          (** Header of level 1 *)
...
| Ul of t list     (** Unumbered list *)
| Ol of t list     (** Ordered (i.e. numbered) list *)
| Ulp of t list
| Olp of t list
...
```

**Comment by pw374** [comment]
Ulp and Olp contain paragraphs, Ul and Ol don't.

We could drop Ulp and Olp, by replacing them with Ul and Ol. But in Markdown, it doesn't make sense to have for instance `Ul[P something; not_a_p]`, and perhaps dropping Ulp and Olp would make it easier to happen...

**Comment by dbuenzli** [comment]
The problem with this representation is that you cannot treat simply treat `Ul` and its contents in a generic fashion you always get two cases to treat.

> But in Markdown, it doesn't make sense to have for instance Ul[P something; not_a_p], and perhaps dropping Ulp and Olp would make it easier to happen...

I don't think you solved any problem with this: someone can still create such a value to encode so you'll need to raise invalid argument anyway. You also make it significantly harder to understand the datatype; for example I don't know if in `Ulp` the `P`'s are there or if they are implied.

**Comment by pw374** [comment]
In Ulp, P is implicit.

I don't mind much if we get rid of Ulp and Olp.

**Comment by pw374** [comment]
However, if we get rid of Ulp and Olp, we'll have to be more careful about the contents of Ul and Ol.
Currently, if there's Ul[P ...], I don't care if it generates crap, because it's not supposed to happen.
If there's no Ulp anymore, it means that `Ul[P a; H1 b]` and `Ul[P a; P[H1 b]]` are the same, and it's a bit weird.

**Comment by dbuenzli** [comment]
> Ul[P a; H1 b] and Ul[P a; P[H1 b]] are the same,

Well do you have another example ? because this is simply invalid html... p  [can](https://www.w3.org/TR/html-markup/p.html) can only contain phrasing content.

IIUC this problem only occurs on output, for me you could either raise `Invalid_argument` or add an implied P. Also note that what you mention doesn't seem to be true in [commonMark](http://spec.commonmark.org/0.26/#list-items) where there are examples of p followed by pre or blockquotes (didn't look into details).
