### ISSUE TITLE
Add support for section wrapping of header identifiers

### ISSUE THREAD

**Issue by clecat** [ocaml/omd#175]
Hello,
I'm currently working on [ocaml-mdx](https://github.com/realworldocaml/mdx) which uses pandoc in order to generate html code from the markdown files.
I want to replace it for omd in order to avoid a Sys.command call and for more portability.
But the problem is that we are using the "--section-divs" argument, which does the following:
> Wrap sections in \<section> tags, and attach identifiers to the enclosing \<section> rather than the header itself.

Generating this:
```
<section id="test0--toto--and-titi" class="level1">
<h1>Test0, -toto- and titi</h1>
<p>toto</p>
</section>
```
Instead of this:
```
<h1 id="Test0-toto-and-titi">Test0, -toto- and titi</h1>
<p>toto</p>
```

As far as I know, omd does not currently support such thing.
Does it seems reasonable to add support for it ? (in the binary and the library API)

**Comment by nojb** [comment]
`omd` was recently rewritten (#174, no release yet) but the new API should allow to add this without much trouble. You would need to do 2 easy things:
1) Rewrite the implementation of the HTML printer to use an open recursion style (https://github.com/ocaml/omd/blob/master/src/html.ml#L135) so that individual cases can be overriden by the library client code, and
2) in `ocaml-mdx` you would need override the `heading` method of the HTML printer to keep track of the section scope and insert the `section` tags as needed.

Neither of the two items are particularly difficult and they would be a nice intro if you are interested to dig a little deeper into `omd`. I am glad to help you along, but I don't have time at the moment to work on them myself.

**Comment by clecat** [comment]
Nice thanks, I will give it a try as soon as possible :)

**Comment by clecat** [comment]
Okay so, does using a functor looks to you ?
Something like that:
We have a base module containing a dumping function for every case of the ast.
We use it for generating a new To_html module via a functor.
And a user who wants to override a function simply creates a module including the base module and redefining the function.

**Comment by nojb** [comment]
That's one possibility. You could also use objects. My preferred approach, however, is to be low-tech and just use records:
```ocaml
type printer =
  {
    block: printer -> Buffer.t -> inline block -> unit;
    paragraph: printer -> Buffer.t -> inline -> unit;
    blockquote: printer -> Buffer.t -> inline block list -> unit;
    (* rest of cases for blocks *)
    inline: printer -> Buffer.t -> inline -> unit;
    html: printer -> Buffer.t -> string -> unit;
    (* rest of cases for inlines *)
  }
```

**Comment by clecat** [comment]
Gave a first shot at it, actually, it may not be enough to do everything I need, but it's a good start (c.f. this original [issue](https://github.com/realworldocaml/mdx/issues/114#issuecomment-487908687): Pandoc uses some extensions which I'm trying to reproduce in omd. It might be more relevant to implement those extensions - which are not part of the commonmark specs - directly in omd as @avsm highlighted)

**Comment by nojb** [comment]
If it is possible to implement these features by using the API (maybe after improving it), I would prefer that. Keeping features to an absolute minimum in the core library is a big win in terms of maintainability and code quality (extensions which have few users tend to bitrot quickly, etc.)

I will take a look at your code shortly.

**Comment by clecat** [comment]
Should we close this issue ?

**Comment by nojb** [comment]
Yes!
