### ISSUE TITLE
Allowing attributes extensions parsing

### ISSUE THREAD

**Issue by clecat** [ocaml/omd#186]
Pandoc supports several extensions allowing the declaration of attributes for various 
purposes, among others:
- [Heading attributes](https://pandoc.org/MANUAL.html#extension-header_attributes)
- [Fenced code attributes](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes)
- [Inline code attributes](https://pandoc.org/MANUAL.html#extension-inline_code_attributes)
- [Link attributes](https://pandoc.org/MANUAL.html#extension-link_attributes)
- [Fenced divs attributes](https://pandoc.org/MANUAL.html#extension-fenced_divs)

Their format which seems to be common to all of them consists in curly brackets containing the needed attributes:
> {.idx}

This format however, is not part of the commonmark specs (apparently discussed [here](https://talk.commonmark.org/t/consistent-attribute-syntax/272) since 2014), and therefore is not implemented in omd.

Could it be possible to extend the parsing of omd, so we could have the parsing of those attributes if asked by the user ?

**Comment by clecat** [comment]
For example as an additionnal optionnal string/string list added in the records.

**Comment by nojb** [comment]
Seems reasonable. If we add this we should add it unconditionally, I want to keep different code paths in the parser and the code in general to the absolute minimum.

To add support for attributes you need to modify the parser. To get started you could start by adding attributes to a paragraph-level node. The simplest is probably the case of headings. You will need to

- modify the function https://github.com/ocaml/omd/blob/master/src/parser.ml#L335-L358 in order to recognize optional attributes at the end of the line. Look at the existing parsers for inspiration.

- propagate this data inside the `Parser.Latx_heading` and `Ast.Heading` constructors.

- adapt the printers (at least the HTML one)

- add some tests

**Comment by clecat** [comment]
Okay thank you for the informations, I will give it a look then

**Comment by avsm** [comment]
Thanks for the guidance @nojb!  A number of these are extremely useful for RWO (which motivates @clecat's request).  We also need to decide whether the ocaml.org content will support these attributes well, before we switch that over to a released omd trunk to generate that. (cc @Chris00)

**Comment by Chris00** [comment]
I do not think supporting these attributes would be a problem for ocaml.org.  Now, since they are not standard markdown, they probably should be optional and turned off by default (in the module interface and for the executable).

**Comment by nojb** [comment]
> Now, since they are not standard markdown, they probably should be optional and turned off by default (in the module interface and for the executable).

I would rather not. Parsing markdown is already complicated and every extra code path increases complexity and the possibility of bugs.

And in any case this features (attributes) will probably end up in official markdown in some form at some point in the future. We can always adjust it later on to conform to the standard.

**Comment by clecat** [comment]
We should close this now :)

**Comment by nojb** [comment]
Fixed in #187
